# Generated by Django 6.0.2 on 2026-02-12 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_name", models.CharField(blank=True, max_length=100)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "expected_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "foreign_currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "foreign_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
