# Generated by Django 6.0.2 on 2026-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_onboardingprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance_goal",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
