# Generated by Django 6.0.2 on 2026-02-12 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="ledger.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet", "occurred_at"],
                        name="ledger_tran_wallet__b30a6f_idx",
                    ),
                    models.Index(
                        fields=["wallet", "action", "occurred_at"],
                        name="ledger_tran_wallet__88d65d_idx",
                    ),
                ],
            },
        ),
    ]
